
CREATE USER [NT SERVICE\MSOLAP$SQLSERVER] FOR LOGIN [NT SERVICE\MSOLAP$SQLSERVER];
ALTER ROLE [db_datareader] ADD MEMBER [NT SERVICE\MSOLAP$SQLSERVER];


ALTER DATABASE MovilityCOVID_SV2020
  SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE MovilityCOVID_SV2020
  SET READ_COMMITTED_SNAPSHOT OFF;


  SELECT DISTINCT [Year]
FROM dbo.Calendar2020;

ALTER DATABASE MovilityCOVID_SV2020
  SET ALLOW_SNAPSHOT_ISOLATION ON;
GO

CREATE TABLE dbo.Region
(
  RegionID   INT   PRIMARY KEY,
  Dpto       NVARCHAR(100),
  
);
